### ISSUE TITLE
edit-config always returns an application error

### ISSUE THREAD

**Issue by zanetworker** [leopoul/ncclient#28]
Hi, 

I have been trying for a while to get edit-conf to function correctly with no luck. For example, consider the following [example](https://github.com/zanetworker/NETCONF_AM/blob/master/AMSoil_NETCONF/src/plugins/netconfrm/netconf_rm.py): 

def demo(host, user):
    snippet = """<config><interfaces><interface><name>eth0</name></interface></interfaces></config>"""
    m= manager.connect(host="localhost", port=830, username='user')
    assert(":validate" in m.server_capabilities)
    print  m.edit_config(target='running', config=snippet)

I get the following reply 
  rpc-error>
    error-type>application</error-type>
    error-tag>operation-failed</error-tag>
    error-severity>error</error-severity>
    error-message>Some unspecified error occurred.</error-message>
  /rpc-error>
/rpc-reply>

I am using netopeer as the server and I define a simple data model for testing. When I use the netopeer client to input the same exact configuration, the operation is successful, but with ncclient rpc calls it is not happening. 

Thank you in advance, 
Adel.

**Comment by abh15** [comment]
If I try to send this using ncclient
'''
snippet='''\<config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
   \<file xmlns="urn:ietf:params:xml:ns:yang:example">
       \<filename>newfile.txt\</filename>
   \</file>
\</config>'''    

'''

then netopeer server returns-

\<rpc-error>
  \<error-type>application</error-type>
   \<error-tag>operation-failed</error-tag>
   \<error-severity>error</error-severity>
   \<error-message>Some unspecified error occurred.</error-message>
\</rpc-error>
\</rpc-reply>

with ncclient throwing-
ncclient.operations.rpc.RPCError: Some unspecified error occurred.

When I send same snippet through netopeer-cli(without \<config>\</config>) it works perfectly well.

**Comment by abh15** [comment]
@leopoul
