### ISSUE TITLE
session.load_known_hosts() takes very long time to finish.

### ISSUE THREAD

**Issue by codeworm2** [leopoul/ncclient#31]
When my user have 500 known hosts, this call takes many minutes.  
https://github.com/leopoul/ncclient/blob/master/ncclient/manager.py#L114

I disabled this call in my code at this moment, hope you can fix it.

**Comment by leopoul** [comment]
Setting `hostkeys_verify = False` at the connection params will now bypass loading of the hosts file (fixed here:  https://github.com/leopoul/ncclient/blob/master/ncclient/manager.py#L113 )

This fix will be included in the upcoming release.

Best,
Leo
