### ISSUE TITLE
Server does not support [:writable-running], but server capabilites has it

### ISSUE THREAD

**Issue by joysboy** [leopoul/ncclient#39]
My server capabilities
```
server_capabilities=['urn:ietf:params:netconf:writable-running', 'urn:ietf:params:netconf:capability:validate:1.0', 'urn:ietf:params:netconf:base:1.0', 'urn:ietf:params:netconf:capability:notification:1.0', 'urn:ietf:params:netconf:capability:interleave:1.0', 'urn:ietf:params:netconf:capability:h3c-netconf-ext:1.0']
```
I want edit config, but ncclient raise "MissingCapabilityError('Server does not support [:writable-running]',)"

https://github.com/leopoul/ncclient/blob/master/ncclient/operations/rpc.py#L328
The string is one part of member in array. The judge result is false.

```python
        flage = False
        for c in self._session.server_capabilities:
            if capability in c:
                flage = True
        if not flage:
            raise MissingCapabilityError('Server does not support [%s]' % capability)
```

**Comment by leopoul** [comment]
Hi,

Your server capabilities seem to differ from the RFC
```
   The :writable-running capability is identified by the following
   capability string:
      urn:ietf:params:netconf:capability:writable-running:1.0
```

and from ncclient's supported capabilities:
https://github.com/leopoul/ncclient/blob/master/ncclient/devices/default.py#L79

You seem to be missing a "capability:1.0" suffix at the writable running part

Best,
L.
