### ISSUE TITLE
Interfacing with a RFC 6241 server

### ISSUE THREAD

**Issue by ttosttos** [leopoul/ncclient#40]
Tried some of the examples (nc0*.py) against an RFC6241 server with no luck.  Couldn't get the proper capability to be sent ("urn:ietf:params:netconf:base:1.1").  Is it even possible with 0.4.2.?  If so, what changes would be required in nc01.py for example.  Thanks!

**Comment by leopoul** [comment]
Hopefully 0.4.4 or 0.4.5 will include support for NETCONF 1.1. Development for this has already begun.
