### ISSUE TITLE
if device doesn't respond for capability exchange, session._post_connect doesn't return

### ISSUE THREAD

**Issue by subhak186** [leopoul/ncclient#47]
SSH to a device was really slow in my network. I find, the method session:_post_connect hangs, if server doesn't respond with capability message. Do we have any workaround or solution for this?

Thanks

**Comment by leopoul** [comment]
Fixed here: https://github.com/leopoul/ncclient/blob/master/ncclient/transport/session.py#L95
It will be include in the upcoming release

Best,
Leo
