### ISSUE TITLE
This is a duplicate for #23 - rpc_error_exempt always expects 'error-message' present

### ISSUE THREAD

**Issue by slieberth** [leopoul/ncclient#68]
many thanks for maintaining & distributing ncclient.

I am working as solution architect and I am preparing for a customer project (juniper & cisco), which will need automation, therefor I am looking in netconf as one option.

- ncclient (0.4.3) works with Junos like a charm :-) 

- towards Cisco 1000v/CSR I am running into errors  - surprisingly it has worked only once, but now when connecting to 1000v/CSR, then I get ncclient exception, please see attached text snippet below.
I am on python 2.7, using sshv2. I am getting the same error message on Mac and Ubuntu

from ncclient import manager
with manager.connect(host="192.168.56.111", port=22, username="admin", password="admin1", 
                    device_params={'name': "csr"},hostkey_verify=False) as m:
    c = m.get_config(source='running').data_xml
    with open("%s.xml" % "vIOS", 'w') as f:
        f.write(c)

$ python vIosNetconf.py 

Traceback (most recent call last):
  File "vIosNetconf.py", line 5, in <module>
    c = m.get_config(source='running').data_xml
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 156, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 226, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/operations/retrieve.py", line 87, in request
    return self._request(node)
  File "/Library/Python/2.7/site-packages/ncclient/operations/rpc.py", line 305, in _request
    self._reply.error.message):
  File "/Library/Python/2.7/site-packages/ncclient/devices/default.py", line 163, in is_rpc_error_exempt
    error_text = error_text.lower().strip()
AttributeError: 'NoneType' object has no attribute ‚lower'

I am happy to debug (and contribute to ncclient code if you wish), if you give me advice, where/how to start.

**Comment by slieberth** [comment]
attached the debug output from the IOS-XR:

vIOS1#
*Jun 10 05:39:10.865: GSI: netconf app _s_ssh.[0x7F0914D544A0]: new ssh connection from 192.168.56.1
*Jun 10 05:39:10.866: NETCONF: ns_clone.sess=0x7F0916484610
*Jun 10 05:39:10.868: NETCONF: naap_accept.clone=0x7F0916484610
*Jun 10 05:39:10.868: NETCONF: _nssd.7.snd.now<?xml version="1.0" encoding="UTF-8"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:capability:writeable-running:1.0</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:url:1.0</capability><capability>urn:cisco:params:netconf:capability:pi-data-model:1.0</capability><capability>urn:cisco:params:netconf:capability:notification:1.0</capability></capabilities><session-id>373835280</session-id></hello>
*Jun 10 05:39:10.868: NETCONF: _nssd.7.snd.don=7F0916484610 msg=7F0916484410
*Jun 10 05:39:10.868: NETCONF: ne_send.sess=0x7F0916484610
*Jun 10 05:39:10.880: GSI: netconf app _s_ssh.[0x7F0908130010]: <?xml version="1.0" encoding="UTF-8"?><nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><nc:capabilities><nc:capability>urn:ietf:params:netconf:capability:writable-running:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capability><nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability><nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:startup:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability></nc:capabilities></nc:hello>
*Jun 10 05:39:10.880: NETCONF: _namn.7.mlc.don=7F091639DFB8
*Jun 10 05:39:10.880: NETCONF: _narc.7.rcv.ok=7F0916484610
*Jun 10 05:39:10.881: NETCONF: netconf_xml_interpret.7.msg_len=1050 bytes
*Jun 10 05:39:10.881: NETCONF: netconf_xml_interpret.7.ok
*Jun 10 05:39:10.881: NETCONF: _nem.7.msg_type=1
*Jun 10 05:39:10.881: NETCONF: netconf hello#3.count=0
*Jun 10 05:39:10.881: NETCONF: _nem.7.nre_type=3
*Jun 10 05:39:10.881: NETCONF: _nmfr.7.now=7F091667FEF8
*Jun 10 05:39:10.881: NETCONF: _nefhm.now=7F091667FEF8
*Jun 10 05:39:10.881: NETCONF: _nefrp.now=7F091667FEF8
*Jun 10 05:39:10.981: GSI: netconf app _s_ssh.[0x7F0908130010]: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:55a932cc-0f34-11e5-b392-48d705e5fcd1"><nc:get-config><nc:source><nc:running/></nc:source></nc:get-config></nc:rpc>
*Jun 10 05:39:10.981: NETCONF: _namn.8.mlc.don=7F091639F228
*Jun 10 05:39:10.981: NETCONF: _narc.8.rcv.ok=7F0916484610
*Jun 10 05:39:10.981: NETCONF: netconf_xml_interpret.8.msg_len=232 bytes
*Jun 10 05:39:10.981: NETCONF: netconf_xml_interpret.8.ok
*Jun 10 05:39:10.981: NETCONF: _nem.8.msg_type=2
*Jun 10 05:39:10.981: NETCONF: _nsv.5.vty=7F09150DEC50 usr=admin priv=1 cvw=0
*Jun 10 05:39:10.981: NETCONF: filter_cfg=[show running ]
*Jun 10 05:39:10.981: NETCONF: _nec.3.vty=7F09150DEC50 usr=admin priv=1 cvw=0
*Jun 10 05:39:10.982: NETCONF: nrg_execute.ctx=0x7F0916484610
*Jun 10 05:39:10.982: NETCONF: _nssd.8.snd.now<?xml version="1.0" encoding="UTF-8"?><rpc-reply message-id="urn:uuid:55a932cc-0f34-11e5-b392-48d705e5fcd1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><rpc-error><error-type>protocol</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity></rpc-error></rpc-reply>
*Jun 10 05:39:10.982: NETCONF: _nssd.8.snd.don=7F0916484610 msg=7F0916484710
*Jun 10 05:39:10.982: NETCONF: ne_send.sess=0x7F0916484610
*Jun 10 05:39:10.982: NETCONF: _nem.8.nre_type=3
*Jun 10 05:39:10.982: NETCONF: _nmfr.8.now=7F091667F718
*Jun 10 05:39:10.982: NETCONF: _nefom.now=7F091667F718
*Jun 10 05:39:10.982: NETCONF: _nefrp.now=7F091667F718
*Jun 10 05:39:11.209: GSI: netconf app _s_ssh.[0x7F0908130010]: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:55cd404a-0f34-11e5-9d68-48d705e5fcd1"><nc:close-session/></nc:rpc>
*Jun 10 05:39:11.209: NETCONF: _namn.9.mlc.don=7F091639DF18
*Jun 10 05:39:11.209: NETCONF: _narc.9.rcv.ok=7F0916484610
*Jun 10 05:39:11.209: NETCONF: netconf_xml_interpret.9.msg_len=184 bytes
*Jun 10 05:39:11.209: NETCONF: netconf_xml_interpret.9.ok
*Jun 10 05:39:11.209: NETCONF: _nem.9.msg_type=2
*Jun 10 05:39:11.209: NETCONF: _nsv.6.vty=7F09150DEC50 usr=admin priv=1 cvw=0
*Jun 10 05:39:11.209: NETCONF: _nssd.9.snd.now<?xml version="1.0" encoding="UTF-8"?><rpc-reply message-id="urn:uuid:55cd404a-0f34-11e5-9d68-48d705e5fcd1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><ok /></rpc-reply>
*Jun 10 05:39:11.209: NETCONF: _nssd.9.snd.don=7F0916484610 msg=7F0916484410
*Jun 10 05:39:11.209: NETCONF: ne_send.sess=0x7F0916484610
*Jun 10 05:39:11.209: NETCONF: ns_stop.gsi_destroy.delayed
*Jun 10 05:39:11.210: NETCONF: _nem.9.nre_type=3
*Jun 10 05:39:11.210: NETCONF: _nmfr.9.now=7F09166817D8
*Jun 10 05:39:11.210: NETCONF: _nefom.now=7F09166817D8
*Jun 10 05:39:11.210: NETCONF: _nefrp.now=7F09166817D8
*Jun 10 05:39:11.312: NETCONF: ns_destroy.sess=0x7F0916484610

**Comment by slieberth** [comment]
This is a duplicate for #23 - rpc_error_exempt always expects 'error-message' present #23

root couse: ncclient expects error-message attribute, hovever IOS-XR is not sending any error-message attribute in the roc reply

could be fixed in nnclient/operations/rpc.py line 82

    @property
    def message(self):
        "The contents of the `error-message` element if present or `None`."
        #edit slieberth
        if self._message == None: self._message = "slieberth: rpc error-message not set"
        return self._message


python vIosNetconf.py 
Traceback (most recent call last):
  File "vIosNetconf2.py", line 76, in <module>
    conn.edit_config(target='running', config=CREATE_VRF)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 156, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 226, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/operations/edit.py", line 67, in request
    return self._request(node)
  File "/Library/Python/2.7/site-packages/ncclient/operations/rpc.py", line 310, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: slieberth: rpc error-message not set

**Comment by slieberth** [comment]
root cause for the problem was the incorrectly configured to support "aaa new-model" configuration on IOS-XR, which gave the netconf ssh user insufficient privileges:
*Jun 10 05:39:10.981: NETCONF: _nsv.5.vty=7F09150DEC50 usr=admin priv=1 cvw=0

when switching to "no aaa new-model", privileges are fine, also the examples work fine

*Jun 10 10:57:00.950: NETCONF: _nsv.2.vty=7FF0EB838A20 usr=admin priv=15 cvw=0

*Jun 10 11:04:18.504: NETCONF: _nssd.8.snd.now<?xml version="1.0" encoding="UTF-8"?><rpc-reply message-id="urn:uuid:712a974f-0f60-11e5-8c4c-48d705e5fcd1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><data><cli-config-data-block>!
! Last configuration change at 10:56:51 UTC Wed Jun 10 2015 by admin
!
version 15.5
service timestamps debug datetime msec
service timestamps log datetime msec
no platform punt-keepalive disable-kernel-core
platform console auto
!
hostname vIOS1
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
!
!
!
!
!
!
!
!
!
ip domain name sl.de
!
!
!
!
!
!
!
!
!
!
subscriber templating
!
multilink bundle-name authenticated
!
!
!
license udi pid CSR1000V sn 905WSM8W58S
spanning-tree extend system-id
!
username admin privilege 15 password 0 admin1
!
redundancy
!
!
!
!
!
!
ip ssh version 2
! 
!
!
!
!
!
!
!
!
!
!
!
!
! 
! 
!
interface GigabitEthernet1
 ip address 192.168.5.6.111 255.255.255.0
 negotiation auto
!
interface GigabitEthernet2
 no ip address
 shutdown
 negotiation auto
!
!
!
ip forward-protocol nd
!
no ip http server
no ip http secure-server
!
!
!
!
control-plane
!
!
line con 0
 stopbits 1
line vty 0 4
 exec-timeout 0 0
 login local
!
netconf ssh
!
</cli-config-data-block></data></rpc-reply>

**Comment by alangregory** [comment]
@slieberth  solved aaa login privilege with:

**line vty 0 4
  authorization exec your-list
  login authentication your-list**
